import Head from "next/head";
import styles from "../styles/Home.module.css";
import Link from "next/link";
import { Club } from "contentlayer/generated";
import styled from "@emotion/styled";
import { css } from "@emotion/react";
import {
	Container,
	Text,
	Heading,
	Box,
	Flex,
	Button,
	Spacer,
	Input,
	InputGroup,
	InputLeftElement,
	InputRightElement,
	Center,
} from "@chakra-ui/react";
import NavBar from "src/components/NavBar";
import ClubCard from "src/components/ClubCard";
import Footer from "src/components/Footer";

export default function Home() {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<CurveBackground />

			<Box marginTop="-850">
				<NavBar />
				<Container as="main" maxWidth="95rem">
					<Flex>
						<Heading color="white" fontWeight="500">
							Find your place where your
							<Text fontWeight="bold">heart beats</Text>
						</Heading>
						<Spacer />
						<CTAButton />
					</Flex>

					<SlideShow />

					<Center
						mt="200"
						color="#555555"
						fontWeight="bold"
						flexDirection="column"
					>
						<Heading fontSize="53">Find and join existing clubs</Heading>
						<SearchBar />
					</Center>

					<ClubCard />
				</Container>
			</Box>

			<Footer />
		</>
	);
}

function fetchClubData(error: any, clubs: Club[]) {
	return (
		<div className={styles.clubs}>
			{error && <h1>Fetch error</h1>}

			{!clubs && !error && <h1>Loading</h1>}

			{clubs &&
				clubs.map((club) => (
					<div key={club._id} className={styles.club}>
						<Link href={club.url}>
							<a className={styles.card}>
								=
								<div className={styles.card_header}>
									=<h2>{club.name}</h2>
									<p>{club.description?.short ?? ""}</p>
								</div>
							</a>
						</Link>
					</div>
				))}
		</div>
	);
}

function CTAButton() {
	return (
		<Button
			bg="#F2779A"
			color="white"
			px="55"
			py="25"
			borderRadius="0"
			borderWidth="4px"
			borderColor="black"
			boxSizing="border-box"
		>
			What is Guilds
		</Button>
	);
}

function SearchBar() {
	return (
		<InputGroup width="47rem" size="lg" borderColor="black">
			<Input
				placeholder={"Search for a club"}
				p="9"
				borderRadius="0"
				borderWidth="4px"
				boxShadow="-7px 7px black"
			/>
			<InputRightElement w="13rem" h="100%">
				<Button
					h="100%"
					w="100%"
					borderRadius="0"
					borderWidth="4px"
					borderColor="black"
					bg="#0057ff"
					color="white"
				>
					Search
				</Button>
			</InputRightElement>
		</InputGroup>
	);
}

function CurveBackground() {
	return (
		<Box
			pos="relative"
			bg="#0057ff"
			h="90vh"
			zIndex="-1"
			_after={{
				content: '""',
				w: "100%",
				h: "70%",
				bg: "white",
				pos: "absolute",
				bottom: "0",
				borderTopLeftRadius: "50%",
				borderTopRightRadius: "50%",
			}}
		/>
	);
}

function SlideShow() {
	return (
		<Box
			h="592px"
			bg="lightgray"
			pos="relative"
			color="white"
			borderWidth="6px"
			borderRadius="50px"
			borderColor="black"
			shadow="47px 47px #7a97ff"
		/>
	);
}
