import Head from "next/head";
import styles from "../styles/Home.module.css";
import Link from "next/link";
import { Club } from "contentlayer/generated";
import useSWR from "swr";
import { fetcher } from "src/utils";
import { Container } from "@chakra-ui/react";
// import Image from 'next/image'
// import { clubAssetURL } from 'src/utils'

export default function Home() {
	const { data: clubs, error } = useSWR<Club[]>("/api/clubs", fetcher);

	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Container>
				<main>
					<h1 className="page-title">Guilds</h1>

					<div className={styles.clubs}>
						{error && <h1>Fetch error</h1>}

						{!clubs && !error && <h1>Loading</h1>}

						{clubs &&
							clubs.map((club) => (
								<div key={club._id} className={styles.club}>
									<Link href={club.url}>
										<a className={styles.card}>
											=
											<div className={styles.card_header}>
												=<h2>{club.name}</h2>
												<p>{club.description?.short ?? ""}</p>
											</div>
										</a>
									</Link>
								</div>
							))}
					</div>
				</main>
			</Container>
		</>
	);
}
