import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { Club, loadClubs } from '../sources/clubs'
import Link from 'next/link'

export default function Home({ clubs }: { clubs: Club[] }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Guilds</h1>
        <ul>
          {clubs.map(club => (
            <li key={club.slug}><Link href={`/clubs/${club.slug}`}>{club.metadata.name}</Link></li>  
          ))}
        </ul>
      </main>
    </div>
  )
}

export async function getStaticProps() {
  return {
    props: {
      clubs: loadClubs()
    }
  }
}